# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
container: "docker://continuumio/miniconda3"



include: "rules/common.smk"
include: "rules/gmap.smk"


rule rna_seq_map_all:
    input:
        get_final_output
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.
